apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-journal-entry
  namespace: trading-journal
data:
  JWT_AUDIENCE: '<JWT_AUDIENCE>'
  JWT_ISSUER: '<JWT_ISSUER>'
  JWT_PUBLIC_KEY: '<JWT_PUBLIC_KEY>'
  MONGO_USER: '<MONGO_USER>'
  MONGO_HOST: '<MONGO_HOST>'
  MONGO_DATABASE: '<MONGO_DATABASE>'
  STORAGE_ENDPOINT: '<STORAGE_ENDPOINT>'
  STORAGE_LOCATION: '<STORAGE_LOCATION>'
  STORAGE_CDN: '<STORAGE_CDN>'


