name: API Tests with postman and newman
on:
  workflow_dispatch:
    inputs:
      iterations:
        description: Number of iterations
        default: "1"
        required: true

jobs:
  test:
    name: Test Latest Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Run Postman collection
        run: |
          newman run postman/TJE.postman_collection.json --insecure -e postman/TJE_test.postman_environment.json n ${{ github.event.inputs.iterations }} -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults